# Generated by Django 3.2.3 on 2023-08-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='check_not_self_follow',
        ),
    ]
