# Generated by Django 3.2.3 on 2023-08-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_subscribe_check_not_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_follow',
        ),
    ]
